name: get_repo-mapping-var_to_env-var_to_var

on: 
  workflow_dispatch:
    inputs:
      user-name:
        description: "which user?"
        required: false
        type: string
        default: "bob"
jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      environ: ${{ steps.get-environ.outputs.environ }}
    steps:
      - name: get env from user input & repo map var
        id: get-environ
        run: |
          environ="${{ inputs.user-name }}"
          echo "environ=$environ"
          echo "environ=$environ" >> "$GITHUB_OUTPUT"
  get_my_var:
    runs-on: ubuntu-latest
    needs: prep
    environment: ${{ needs.prep.outputs.environ }}
    steps:
      - name: Get myVar
        run: |
          echo "MAP=${{ vars.MAP }}"
          echo "MY_VAR=${{ vars.MY_VAR }}"
          myVarVal=$(echo '${{ vars.MY_VAR }}' | jq -r --arg key ${{ inputs.user-name }} '.[$key]')
          echo "myVarVal=$myVarVal"
